baseURL = "https://phillc.com/"
languageCode = "en-us"
defaultContentLanguage = "en-us"
title = "Phillip Campbell"
theme = []
googleAnalytics = "UA-4379922-3"

[permalinks]
  post = "/blog/:year/:month/:day/:slug/"

[taxonomies]
  # tag = "tags"
  # category = "categories"
  archive = "archives"

[author]
  name = "Phillip Campbell"
  location = "Atlanta"
  # Your profile picture
  # Overwritten by your gravatar image if `author.gravatarEmail` is filled
  # picture = "https://cdn1.iconfinder.com/data/icons/ninja-things-1/1772/ninja-simple-512.png"
  # Your Twitter username without the @. E.g : thibaudlepretre
  twitter = "phillc"